import Head from "next/head"

export default function Home() {
  return (
    <>
      <Head>
        <title>Fake Space</title>
        <meta name="description" content="Generated by create next app and Mauricio's noggin" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Fake Space</h1>
      </main>
    </>
  )
}
